---
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  always_update_cookbooks: true
  log_level: "<%= ENV['CHEF_LOG_LEVEL'] || 'info' %>"
verifier:
  name: inspec
  format: "<% if ENV['INSPEC_DEBUG'] %>documentation<% else %>junit<% end %>"
  output: "<% if ENV['INSPEC_DEBUG'] %>-<% else %>test/metadata/junit/acceptance/TEST-%{platform}-%{suite}.xml<%
    end %>"
platforms:
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: centos-7.2
- name: centos-6.5
suites:
- name: complex-case-1
  run_list:
  - alum-testing::acceptance
  attributes:
    history: complex/case-1
  verifier:
    inspec_tests:
    - name: complex case 1
      path: test/suites/acceptance/default
    attributes:
      history: complex/case-1
